[tool.poetry]
name = "commodore"
version = "v0.0.0"
description = "Commodore is a wrapper around Kapitan which allows compiling a Kapitan inventory from multiple Git repositories"
authors = ["Simon Gerber <simon.gerber@vshn.ch>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.8"
kapitan = "^0.27.0"
click = "*"
cookiecutter = "*"
gitpython = "*"
requests = "*"
url-normalize = "^1.4.1"

[tool.poetry.dev-dependencies]
tox = "*"
autopep8 = "*"
python-dotenv = "*"

[tool.poetry.scripts]
commodore = 'commodore.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
